# Generated by Django 5.1.7 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='uploaded_by',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
